name: Check Flake
on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        # Run all actions relative to the nix/ directory
        working-directory: ./nix
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Check Flake
        run: nix flake check

