name: Check Flake
on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        # Run all actions relative to the nix/ directory
        working-directory: ./nix
    steps:
      - uses: actions/checkout@v3

      - name: Cache Nix store
        uses: actions/cache@v3
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: ${{ runner.os }}-nix-store-${{ hashFiles('nix/flake.lock', 'nix/flake.nix') }}

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: "Import Nix store cache"
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: "nix copy --from /tmp/nixcache .#"

      - name: Check Flake
        run: nix flake check

      - name: "Export Nix store cache"
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: "nix copy --to /tmp/nixcache .#"
