name: Check Flake
on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        # Run all actions relative to the nix/ directory
        working-directory: ./nix
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Cache install Nix packages
        uses: mtoohey31/cache-flake-attrs@v2.0.0
        with:
          key: ${{ runner.os }}-nix-${{ hashFiles('./nix/flake.lock', './nix/flake.nix') }}

      - name: Check Flake
        run: nix flake check

